### ISSUE TITLE
Wigglers 1: Display trajectories & calculate spectrum

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#104]
I split the upgrades for the wigglers in two issues, this is the first one.

The first one consist in displaying the magnetic field, electron velocity, electron trajectory and curvature. And also spectrum.

All are available in the tmp.traj file created by srxraylib.sources.srfunc.wiggler_trajectory. 

This code may help to plot:

```
import numpy


data = numpy.loadtxt("tmp.traj",skiprows=15)
from matplotlib import pylab as plt

fig = plt.figure(1)

fig.add_subplot(221)
plt.plot(data[:,1],data[:,0])
plt.title("Electron trajectory x(y)")
plt.xlabel("Y [m]")
plt.ylabel("X [m]")

fig.add_subplot(222)
plt.plot(data[:,1],data[:,3])
plt.title("Electron velocity betax(y)")
plt.xlabel("Y [m]")
plt.ylabel("betaX")

fig.add_subplot(223)
plt.plot(data[:,1],data[:,6])
plt.title("Electron curvature")
plt.xlabel("Y [m]")
plt.ylabel("curvature [m^-1]")

fig.add_subplot(224)
plt.plot(data[:,1],data[:,7])
plt.title("Magnetic Field (in vertical) Bz(y)")
plt.xlabel("Y [m]")
plt.ylabel("B [T]")

plt.show()

out_object = "tmp.traj"
```

It could be possible to add the 4 plots in a new tab in the middle of "plots" and "output", or add 4 individial tabs. The later solution is more helpful because sometimes we want to zoom and get numerical values from the plot (it will be needed for the next upgrade).

The spectrum can be calculates as (energy limits are already available, you need to add the electron current, and may be the number of points (our you could hard-code it to 500, for example)): 
```
from srxraylib.sources import srfunc
import numpy
import matplotlib.pylab as plt

t1 = numpy.loadtxt("tmp.traj"),skiprows=15)
t1 = t1.T

e, f1 = srfunc.wiggler_spectrum(t1,enerMin=100.0,enerMax=100000.0,nPoints=100,electronCurrent=0.2, outFile="spectrum.dat", elliptical=False)
print(f1)
plt.figure(2)
plt.loglog(e,f1,'r',label="")

plt.title("ESRF wiggler spectrum")
plt.xlabel("E [eV]")
plt.ylabel("Flux[phot/s/0.1%bw]")
ax = plt.subplot(111)
ax.legend(bbox_to_anchor=(1.1, 1.05))
plt.show()
```

**Comment by lucarebuffi** [comment]
Please check it out!

**Comment by srio** [comment]
Beautiful!!

Thanks a lot. I admire how fast you are. 


PS: another small request: when Use emittances=No, all the emittance values should become insensitive.
