### ISSUE TITLE
Wigglers 2: correct the orbit

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#105]
The calculations of the wiggler trajectories is basically:

Magnetic field B is the input or computed as a sinusoidal function
Electron velocity (betax) is proportional to the integral of B
Electron trajectory (x) is the integral of betax. 
Curvature is proportional to B

However, one can add a constant term in the integration processes. This has to be done if we want to correct the orbit, i.e., define the input position of the trajectory and the input direction (~velocity). 

For that, I added new keywords in wiggler_trajectory (need to update SR-xraylib):

```
def wiggler_trajectory(b_from=0, inData="", nPer=12, nTrajPoints=100, \
                       ener_gev=6.04, per=0.125, kValue=14.0, trajFile="",
                       shift_x_flag=0,shift_x_value=0.0,
                       shift_betax_flag=0,shift_betax_value=0.0):
    r"""
...
    :param shift_x_flag: a flag to indicate how to shift x (electron transversal coordinate):
                        0 = No shift
                        1 = Half excursion
                        2 = Minimum
                        3 = Maximum
                        4 = Value at zero
                        5 = User value
    :param shift_x_value: The user value for shift x (if shift_x_flag=5)
    :param shift_betax_flag: a flag to indicate how to shift the betax coordinate (electron transversal velocity):
                        0 = No shift
                        1 = Half excursion
                        2 = Minimum
                        3 = Maximum
                        4 = Value at zero
                        5 = User value
    :param shift_betax_value: The user value for shift betax (if shift_betax_flag=5)
...    """
```

The idea is to add this in the interface to allow the user to "correct" interactively the orbit bu looking at the trajectory and betax plots. This helps to "align" the beamline with the part of the wiggler that we want. For "normal" wigglers, only a shift in x is needed, but for other wigglers including BM radiation (like those I am calculating) I need also to change the betax. 

Many thanks!!!!

**Comment by lucarebuffi** [comment]
I am ready to do the modification, please upgrade SR-xraylib.

**Comment by srio** [comment]
Thanks a lot, Luca. It is beautiful!!!

One small thing: 
The "Shift transversal coordinanes" Value is in meters (because magnetic field is vs meters). 
The "Shift transversal velocity" Value has not units (it is in fact beta=velocity/c)

It is not documented that the magnetic field map must be against coordinate in meters.  May be it could help that in the label Type: "B from file" you could say: Type:"B from file (y[m],Bz[T])" to indicate what should be provided in the file. 

Two cosmetic things (which are not important): 
i) The new section (Electron Beam Parameters) could first present the velocity and second the coordinate (now is first coordinate and then velocity). The reason is that a change in velocity affects the the coordinate, so the user must first adjust velocity, run and check, and then adjust coordinate.
ii) The " widget plots" tabs could be arranged from simple to more elaborated: 
magnetic field, electron curvature, electron velocity, electron trajectory, wiggler spectrum 

Thanks a lot, it is really nice!!!!
