### ISSUE TITLE
about the loop

### ISSUE THREAD

**Issue by tyjisinap** [lucarebuffi/ShadowOui#107]
When I use a Loop Point, I found that the memory will be used out, and the I have to force quit the Oasys.  I test with only source and one optics without any plot and accumulate point, it is the same.  I think every loop should use fixed memory, except there are accumulate parts.

**Comment by tyjisinap** [comment]
does that mean every run use different variable? and it can't be free by the python.

**Comment by lucarebuffi** [comment]
I runned loops of a complete beamline + XRPD simulation, together with several plots (accumulating rays), for an entire night without any problem, with a 8 Gb RAM computer. It is for sure a memory consuming process, but I never found such a problem. Could you please send me your OWS file?

Are you sure that is a memory problem and not a CPU problem?

**Comment by tyjisinap** [comment]
I  use two computer(Ubuntu 14.04,   one is i5 3427U with 4GB mem, the other is i5 4210M with 12GB) and have similar problem,  I monitor the memory and when loop run until the  memory is  used out ,software will be dead.  i found this problem when ran a complicated ows, but when I test with simplest  ows, it is the same . I will send a ows tomorrow morning. Thank you!

**Comment by tyjisinap** [comment]
By the way which OS do you use?

**Comment by tyjisinap** [comment]
This is the ows file. Thank you very much! 

[Oasys.tar.gz](https://github.com/lucarebuffi/ShadowOui/files/153867/Oasys.tar.gz)

**Comment by tyjisinap** [comment]
I set the rays to 500000,it is very quick to use all of my RAM  and swap.

**Comment by lucarebuffi** [comment]
I will check it, but why looping with 500000 rays? the scope of looping is accumulate results of tens of repeated simulations with a few rays (1000 - 10000).

**Comment by tyjisinap** [comment]
I want to raytrace the bent-crystal of polychromator, I think it need many rays. The ows is I trace a ED-XAS beamline with a hyperbolid laue crystal, but I don't know how to use the crystal and raytrace directly, so I use  hyperbolid mirror and script. I don't know whether it is right or not. I will appreciate if you can give me some suggestion about it. Thank you!

**Comment by lucarebuffi** [comment]
The problem is that you have the Detailed Plots activated in all the widgets of the loop. 
Matplotlib, unfortunately, has a huge memory leakage problem, well known in literature.
Select "No Plots" in all the widgets as shown in figure. Disable also all the plotting widgets in the loop (Plot XY 7 in your example).
With this  setup memory usage fluctuate around a fixed value during the loop execution.

![screen shot 2016-03-07 at 14 30 07](https://cloud.githubusercontent.com/assets/6713598/13570847/24171946-e471-11e5-98b5-b5ce4ac2f0cd.png)

**Comment by tyjisinap** [comment]
Thank you very much! it works fine now.
several days ago, I also found some version of numpy in the anaconda python cause the python script crash,  and the version from pip  works fine.
