### ISSUE TITLE
Rename method name in Wavefront1D

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#112]
I  renamed some methods in SRxxraylib/wavefront, but kept an old one for compatibility. So, in the next changes of shadowOui change "wavefront1D.get_amplitude_from_abscissas" by "wavefront1D.get_interpolated_complex_amplitudes". Both are identical now.

Nothing urgent!!

**Comment by lucarebuffi** [comment]
This method was not used in ShadowOui....easy to fix :D
