### ISSUE TITLE
Gaussian Undulator

### ISSUE THREAD

**Issue by RubenReininger** [lucarebuffi/ShadowOui#116]
What equations you use for the Gaussian undulator?
[Print.pdf](https://github.com/lucarebuffi/ShadowOui/files/462344/Print.pdf)

I thought those in the file are the ones I discussed with Manuel

**Comment by srio** [comment]
We use the formulas from Elleaume with the "numerical coefficients", before approximating to multipliers of pi. I believe they are the more exact ones, of course assuming Gaussian approximation of the undulator peaks. 

In https://github.com/lucarebuffi/ShadowOui/blob/master/orangecontrib/shadow/widgets/sources/ow_undulator_gaussian.py

you have: 

        # calculate sizes of the photon undulator beam
        # see formulas 25 & 30 in Elleaume (Onaki & Elleaume)
        s_phot = 2.740/(4e0*numpy.pi)*numpy.sqrt(undulator_length*lambda1)
        sp_phot = 0.69*numpy.sqrt(lambda1/undulator_length)

        photon_h = numpy.sqrt(numpy.power(sigma_x*user_unit_to_m,2) + numpy.power(s_phot,2) )
        photon_v = numpy.sqrt(numpy.power(sigma_z*user_unit_to_m,2) + numpy.power(s_phot,2) )
        photon_hp = numpy.sqrt(numpy.power(sigdi_x,2) + numpy.power(sp_phot,2) )
        photon_vp = numpy.sqrt(numpy.power(sigdi_z,2) + numpy.power(sp_phot,2) )

        return (photon_h/user_unit_to_m, photon_v/user_unit_to_m, photon_hp,photon_vp)

**Comment by srio** [comment]
We checked the Gaussian undulator works well.
