### ISSUE TITLE
after updating oasys I cannot start it

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#120]
In LINUX, I did "git pull" in Oasys, it updated, and then I get the errors below. Any idea? 

I think the problem is in the platform dependence here:
oasys1/oasys/canvas/mainwindow.py
```
if sys.platform == "darwin":
            file_menu = self.menuBar().children()[1]
else:
            file_menu = self.menuBar().children()[2]


```

gurb:/scisoft/XRayOptics/OASYS_VE_GURB % ./start_oasys.sh 
Activating configuration for <class 'oasys.canvas.conf.oasysconf'>
Setting up Canvas main window.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
'CanvasScene(objectName='', ...)' cleared.
'CanvasScene(objectName='', ...)' intitialized.
Setting registry 'None on 'CanvasScene(objectName='', ...)'.
Setting scheme '<oasys.canvas.widgetsscheme.OASYSWidgetsScheme object at 0x7f9b7d7148b8>' on 'CanvasScene(objectName='', ...)'
Stack transition start ()
Stack transition finished ()
Dock transition finished (new width 58)
Dock transition started.
Time from last update 17057 days, 10:41:53.332255 (0)
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mntdirect/_scisoft/XRayOptics/OASYS_VE_GURB/oasys1/oasys/canvas/__main__.py", line 437, in <module>
    sys.exit(main())
  File "/mntdirect/_scisoft/XRayOptics/OASYS_VE_GURB/oasys1/oasys/canvas/__main__.py", line 243, in main
    canvas_window = OASYSMainWindow()
  File "/mntdirect/_scisoft/XRayOptics/OASYS_VE_GURB/oasys1/oasys/canvas/mainwindow.py", line 352, in __init__
    file_menu = self.menuBar().children()[2]
IndexError: list index out of range
gurb:/scisoft/XRayOptics/OASYS_VE_GURB %

**Comment by lucarebuffi** [comment]
Io l’ho aggiornato ieri e non ho alcun problema..

Che versione di Linux è?


-- 

Luca Rebuffi, Ph.D.
X-ray Optics Laboratory Supervisor

Elettra-Sincrotrone Trieste S.C.p.A
Strada Statale 14 - km 163,5 in AREA Science Park
34149 Basovizza, Trieste ITALY
Tel. +39 040 375 85 44 (office)
Tel. +39 040 375 88 48 (lab)
Tel. +39 040 375 85 12 (lab)
Mob. +39 366 656 15 21 (cod.int. #89881)

**Comment by lucarebuffi** [comment]
![screen shot 2016-09-13 at 13 51 02](https://cloud.githubusercontent.com/assets/6713598/18472997/dcea5706-79ba-11e6-975c-07580c62a753.png)

**Comment by lucarebuffi** [comment]
![screen shot 2016-09-13 at 14 05 26](https://cloud.githubusercontent.com/assets/6713598/18473050/2c19bf74-79bb-11e6-90a0-1b86b71e4b4f.png)

**Comment by srio** [comment]
It works in Ubuntu but fails in debian8: 
gurb:/scisoft/XRayOptics/OASYS_VE_GURB % cat /etc/lsb-release
# This file is managed with puppet, do not edit by hand.
DISTRIB_ID=Debian
DISTRIB_DESCRIPTION="Debian GNU/Linux 8.5 (jessie)"
DISTRIB_RELEASE=8.5
DISTRIB_CODENAME=jessie



In fact, the result of 
 print(">>>>",len(self.menuBar().children() ))

is 3 in ubuntu but 2 in debian. 

So, you can write 

`        if sys.platform == "darwin":
            file_menu = self.menuBar().children()[1]
        else:
            file_menu = self.menuBar().children()[-1]
`

**Comment by lucarebuffi** [comment]
ok, i'll do it immediately.

**Comment by lucarebuffi** [comment]
Oasys 0.1.20 is on pypi. Please try it.
