### ISSUE TITLE
Sources crashes under linux when Files to write out is set to Debug

### ISSUE THREAD

**Issue by lucarebuffi** [lucarebuffi/ShadowOui#122]
Possible problem is in method Shadow.Source.write(). Problem doesn't occur in Mac

I tried to fix the problem with a call to self_repair method in ShadowOE and ShadowSource, but it didn't work.

**Comment by srio** [comment]
I know the problem. I spent some time without success:


https://github.com/srio/shadow3/issues/11

**Comment by lucarebuffi** [comment]
I inhibit the Debug mode on Linux until the problem is fixed
