### ISSUE TITLE
Execute all preprocessors widget: error when using waviness

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#126]
![image](https://cloud.githubusercontent.com/assets/502315/19005568/97cd427e-875b-11e6-80ab-f6a61a6cf411.png)

![image](https://cloud.githubusercontent.com/assets/502315/19005618/d35635bc-875b-11e6-9250-a5c03cc72f0b.png)

**Comment by lucarebuffi** [comment]
This is a good example of clamorous bug!

**Comment by srio** [comment]
I can make an slide!! :)

**Comment by lucarebuffi** [comment]
ahahahha
