### ISSUE TITLE
preprocessor waviness: add Ruben Reininger's way to calculate waviness

### ISSUE THREAD

**Issue by lucarebuffi** [lucarebuffi/ShadowOui#13]
The result is much smoother in the sagittal direction (more physical?). Input form accept two slope errors (tangential and sagittal).

**Comment by srio** [comment]
I will write the python code

**Comment by lucarebuffi** [comment]
Added Surface Error Profile widget

**Comment by lucarebuffi** [comment]
Profile from 1D Profile not properly working: check!
