### ISSUE TITLE
Preprocessing python script for alignment

### ISSUE THREAD

**Issue by ddennetiere** [lucarebuffi/ShadowOui#131]
As I discussed with Dr. Sanchez del Rio at SOS, I would be nice (even vital) to have the possibility to change an OE parameter with a python script that would execute at each global shadow run. 
That would for example allow for energy scans with automatic realignement.
Of course the preprocassing would need to get the source parameter in in_object.
![pypreproc](https://cloud.githubusercontent.com/assets/22654323/19144998/18eefeba-8bad-11e6-83cf-d418706db136.png)

**Comment by tyjisinap** [comment]
To Luca,
is there a method to do this in graghic interface? I usually use the info to get the python script, then run the pure python script.

**Comment by lucarebuffi** [comment]
Yes! just use the Python Script widget, in the first group of widgets: 

![screen shot 2016-12-01 at 16 45 32](https://cloud.githubusercontent.com/assets/6713598/20800377/9e86137e-b7e5-11e6-8f36-10305a504e1f.png)

**Comment by lucarebuffi** [comment]
this widget accept up to 10 different inputs (whatever type of data) and send one object in output that can be used, if properly created, by other widgets.

**Comment by lucarebuffi** [comment]
Dear David,

Here something prototyping what you need. In the close future we will introduce the concept of a scanning variable into the looping mechanism. 

![screen shot 2016-12-05 at 09 50 42](https://cloud.githubusercontent.com/assets/6713598/20878696/9e996e5e-bad0-11e6-9b64-77d56c618d24.png)

the python script widget accepts as input both the beam from the grating and the beam from the source and is able to access all the parameters needed:

![screen shot 2016-12-05 at 09 50 53](https://cloud.githubusercontent.com/assets/6713598/20878724/bde95cba-bad0-11e6-8c0c-9d04b080e487.png)

**Comment by lucarebuffi** [comment]
Here is the "template" code that allows you to read/write variables of OEs and sources and to redo the ray-tracing calculation. 

```
from orangecontrib.shadow.util.shadow_objects import ShadowBeam

shadow_beam_from_oe = in_object_1
shadow_beam_from_source = in_object_2

# ACCESS THE PREVIOUS SHADOW OE:
history_entry = shadow_beam_from_oe.getOEHistory(shadow_beam_from_oe._oe_number)

# ACCESS THE OE OBJECT BEFORE OR AFTER TRACING:
shadow_oe_before = history_entry._shadow_oe_start
shadow_oe_end = history_entry._shadow_oe_end

# DUPLICATING THE ORIGINAL OBJECTS IF WANTED:
shadow_oe_before = shadow_oe_before.duplicate() # no changes to the original object!
shadow_oe_end = shadow_oe_end.duplicate() # no changes to the original object!

# ACCESS SOURCE INFORMATION
source = shadow_beam_from_source.getOEHistory(0)._shadow_source_start.src

# ACCESS SHADOW SOURCE VARAIBLES:

print(source.FDISTR)

# ACCESS SHADOW OE VARIABLES:
    
oe = shadow_oe_before._oe

print(oe.FMIRR) # READ

oe.T_INCIDENCE = 10.0 # WRITE

# RETRACE WITH MODIFIED OE:

shadow_beam_out = ShadowBeam.traceFromOE(history_entry._input_beam, shadow_oe_before)

out_object = shadow_beam_out
```

**Comment by ddennetiere** [comment]
Thank you very much for taking care of this issue ! 

Is there a way to use the beam out of the beamline and the beam out of an oe to implement some kind of optimizing feedback loop ?
Anyway, I mark this issue as closed.

Great job guys !

**Comment by lucarebuffi** [comment]
Not now. All the ingredients are there, but they have not put together, yet.
In this moment, there is a looping mechanism, and you can put scripts wherever you want.
In order to do what you need NOW, there is a possibility:

![screen shot 2016-12-05 at 12 01 18](https://cloud.githubusercontent.com/assets/6713598/20882772/eacd8384-bae2-11e6-903f-e75f3c00f0ba.png)

You can put a loop containing your optimizer. Since the python script is not able to keep in memory informations from iteration to iteration, you have to save the critical parameters of every iteration on the file system (in a text file, by example), in order to reuse them in the next iteration for optimization purposes. The loop can be interrupted by the script if the optimization is reached, by sending the proper signal to the loop widget.

**Comment by lucarebuffi** [comment]
If you send me the workspace file and, in detail, the algorithm for optimization, I can write down something for you in a reasonable time.

**Comment by tyjisinap** [comment]
Dear Luca,
Can I change the parameters in the start.xx just like the shadowvui to do such a loop? 
Best regards.

**Comment by lucarebuffi** [comment]
If you do something like this with ShadowOui, I will do "sappuku" like a japanese samurai, then I'll come back as a ghost to haunt your home and scream every night: "WE GOT RID OF FILES!!!!".

**Comment by lucarebuffi** [comment]
Take a look at the code:

 `# ACCESS SOURCE INFORMATION
source = shadow_beam_from_source.getOEHistory(0)._shadow_source_start.src

# ACCESS SHADOW SOURCE VARAIBLES:

print(source.FDISTR)

# ACCESS SHADOW OE VARIABLES:
    
oe = shadow_oe_before._oe

print(oe.FMIRR) # READ

oe.T_INCIDENCE = 10.0 # WRITE
`

As you can see, the object ShadowBeam that is going through the wires, contains a reference to the entire history of the simulation, and allows you to access also the source or the optical elements that produced that beam, before and after the ray-tracing. These objects come from Shadow3, the kernel, and they are a collection of variables identical to those "start.xx" files. If you modify them, as you would have done with those files, during a loop, you will obtain the same result, but in the proper way.
