### ISSUE TITLE
Gratings: allow to read reflectivity (efficiency) from an external file

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#133]
Suggested by Kurt Kummer, it would be nice to enter grating efficiency from external file. 

Therefore, similarly to crystals and mirrors, the widget should accept efficiency from external files. 

The file could contain two columns: energy in eV and efficiency (in 0 to 1 range).

**Comment by lucarebuffi** [comment]
linked to #110

**Comment by lucarebuffi** [comment]
Added in the "Diffraction Setting" Tab of the gratings parameters
