### ISSUE TITLE
Ellipsoidal mirror: remove congruence check

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#134]
The ellipsoidal mirror gives me this error when connecting it to other elements and has surface shape: internal/calculated:

 

![image](https://cloud.githubusercontent.com/assets/502315/19240880/a2dae618-8f0c-11e6-9017-f4ecdb2b40df.png)

It should not appear, as the ellipsoid includes naturally the sagittal bending

**Comment by lucarebuffi** [comment]
Yes, but the algorithm include only spherical radius calculation. Need to find equations also for the ellipse case: semi-major axis and semi-minor axis.

**Comment by srio** [comment]
For the ellipsoid there is no difference between tangential or sagittal. The same ellipsoid focuses in both planes. Therefore, the parameters are the same. The ellipse semiaxes apply only to tangential focusing. One cannot focus in sagittal with an ellipse: the ideal form for sagittal focusing is the circle, which corresponds to the sections of the ellipsoid perpendicular to the axis that goes through the foci. If cylindrical is selected, shadow takes care of putting zeroes at the right coefficients, so nothing should be done. 

The same apply for the hyperboloid, and toroidal mirror. The only case where there is differences is the spherical which contains only one parameter (radius). So spherical is the only case where this test apply and it is the only case where this congruence test should be done.

**Comment by lucarebuffi** [comment]
thus you mean that I have just to send parameters to Shadow3 and go?

**Comment by srio** [comment]
Yes, you do not have to calculate or do anything.

**Comment by lucarebuffi** [comment]
done
