### ISSUE TITLE
plotXY: unexpected error mesage 

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#136]
When selecting to plot column 30 (S0-stokes) or 32 (S2) or 33 (S3) I get: 

![image](https://cloud.githubusercontent.com/assets/502315/19352660/eaf93ad4-9160-11e6-8641-56c2c3f606fd.png)

**Comment by lucarebuffi** [comment]
I don't have this error. Could you please send me the workspace that gives it?

**Comment by srio** [comment]
OK, I found the problem. It is because I have Cartesia Axis = Yes. 

If I put Cartesian Axis = No it works well. 

However, it would be nice to see why it does not manage to set cartesian limits (I understand that it has no much sense, it also happens for col23 and some others). May be change the message "Data not plottable: No good rays, bar content, bad limits or axes"

**Comment by lucarebuffi** [comment]
why not inibit the plotting when the conditions occur with a dedicated message? It's easy to implement.

**Comment by lucarebuffi** [comment]
I changed my mind, only changed the message.
