### ISSUE TITLE
PreMLayer number of bilayers cannot be changed

### ISSUE THREAD

**Issue by xianbo** [lucarebuffi/ShadowOui#140]
In the PreMLayer preprocessor, the number of bilayers is locked at 70. It cannot be changed to other values.
Also, the complex refractive indices calculated from the OASYS version are slightly different from the ones calculated with the Pre_MLayer module in SHADOWVUI.

**Comment by lucarebuffi** [comment]
1 - I didn't find this error: I can input the number of bilayers I want, and generate the file. Could you please send me your ows? 

2 - Sure, the algorithm has been rewritten by Manolo, it is probably more correct now...

**Comment by lucarebuffi** [comment]
![screen shot 2016-10-18 at 12 10 13](https://cloud.githubusercontent.com/assets/6713598/19473444/fa8b23f8-952b-11e6-9e7c-112f3e4b6894.png)

**Comment by xianbo** [comment]
Strange, I reinstalled OASYS and it works now. I don't know what happened to my old version......
