### ISSUE TITLE
Hybrid focusing optical element problem

### ISSUE THREAD

**Issue by xianbo** [lucarebuffi/ShadowOui#141]
Luca, just want to log this issue.
When a height profile simulator or DABAM height profile is linked to a mirror, it automatically turn off the surface error in the ray tracing process for HYBRID calctype 3 (Focusing Optical Element + Slope Errors). I think we should do the same for clactype 2 (Focusing Optical Element ). 
I added the following two lines in the hy_readfiles function.
"
        elif input_parameters.ghy_calcType == 2: 
            shadow_oe._oe.F_RIPPLE = 0
"
right before the text below
"
        elif input_parameters.ghy_calcType == 3: # mirror + figure error
            if input_parameters.ghy_usemirrorfile == 0: # use EMBEDDED one in OE
                if shadow_oe._oe.F_RIPPLE == 1 and shadow_oe._oe.F_G_S == 2:
                    input_parameters.ghy_mirrorfile = shadow_oe._oe.FILE_RIP
"

**Comment by lucarebuffi** [comment]
done
