### ISSUE TITLE
Same parameters different answer

### ISSUE THREAD

**Issue by RubenReininger** [lucarebuffi/ShadowOui#144]
Dears Luca and Manuel,
Thanks for correcting the wiggler units to mm.
I believe I mentioned this issue to Manuel. 
If you run a source with the same parameters it should give the same result. **They are close but not exactly the same.** This is not the case even for the saved file nor for the plots in Oasys.
I attach the ows file and two screen shots.

Ruben
[Changing output.ows.zip](https://github.com/lucarebuffi/ShadowOui/files/606865/Changing.output.ows.zip)
![screen shot 2016-11-22 at 9 46 13 am](https://cloud.githubusercontent.com/assets/15108247/20530752/072bfbd0-b09a-11e6-935b-af43c6958b09.png)
![screen shot 2016-11-22 at 9 45 38 am](https://cloud.githubusercontent.com/assets/15108247/20530753/0739155e-b09a-11e6-8e9b-575b2d488488.png)

**Comment by srio** [comment]
Yes, this issue is for me: 

it is in shadow3. When running shadow3 from python it does not reset the random number generator with the seed. Therefore the seed is used only once after opening Oasys. I will look into it.

**Comment by srio** [comment]
On 11/23/2016 12:09 AM, Reininger, Ruben wrote:
> I am running the example of hybrid using SHADOWVUI. I run it twice and I get slightly different results. 
> Is this related to the previous issue?
>
> Best regards,
>
> Ruben

It is similar but not the same:

in shadowVUI the source does not change, but there is a random process in adding the divergence to the rays in the hybrid mode.

This is also true in python/ShadowOui.

It is therefore interesting to be able to define the random seed also in the hybrid. So there is also an action for Luca+Xianbo when looking into hybrid. 

I agree with you that the simulations should be deterministic, in the sense that we get the same results running twice the same simulation with the same seeds.

**Comment by RubenReininger** [comment]
Thank you Manuel

Ruben
Sent from my IPad

On Nov 23, 2016, at 03:04, Manuel Sanchez del Rio <notifications@github.com<mailto:notifications@github.com>> wrote:


On 11/23/2016 12:09 AM, Reininger, Ruben wrote:

I am running the example of hybrid using SHADOWVUI. I run it twice and I get slightly different results.
Is this related to the previous issue?

Best regards,

Ruben

It is similar but not the same:

in shadowVUI the source does not change, but there is a random process in adding the divergence to the rays in the hybrid mode.

This is also true in python/ShadowOui.

It is therefore interesting to be able to define the random seed also in the hybrid. So there is also an action for Luca+Xianbo when looking into hybrid.

I agree with you that the simulations should be deterministic, in the sense that we get the same results running twice the same simulation with the same seeds.

**Comment by srio** [comment]
I have changed shadow3 to fix this problem. 
So, next time you reinstall shadow3 from github will be fine. 
I remind that setting seed=0 means that the seed is read from the computer clock, so every time will be different. If seed is any other value, different runs will give the same result.

Luca: 
as some behaviour could change, I suggest: 

- In the widget sources replace the label "Seed " by "Seed (0 for automatic)" or "Seed (0=clock)"
- A problem may happen with the loops. If seed is not zero, different runs will cause the same output. So I suggest than when running any source in a loop, the loop tool sets initiaization of the seed from the clock, so ISTAR1=0
