### ISSUE TITLE
problem with setup.py (getsitepackages)

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#145]
I am reinstalling Oasys in virtual environment (Ubuntu 14.04 LTS) and I find a problem 

if I install add-ons from sources I do: 

```
git clone ...
cd shadowOui
python setup.py build
python setup.py install
````

I have a problem because setup uses site.getsitepackages() which is not found. I googled it and it is a problem of the virtualenv. In fact, it is OK outside the VE: 

```
chac:~/tmp % 
chac:~/tmp % python3
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site.getsitepackages()
['/usr/local/lib/python3.4/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.4/dist-packages', '/usr/lib/dist-python']
>>> exit()
chac:~/tmp % 
chac:~/tmp % source ~/OASYS_VE/oasys1env/bin/activate
(oasys1env)chac:~/tmp % python
Python 3.4.0 (default, Jun 19 2015, 14:20:21) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site.getsitepackages()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getsitepackages'
>>> 
```

Any idea? (in the past I used python setup.py develop instead but seems that does not work either!!
Remember I cannot install add-ons from Oasys, because the firewall. 

Thanks for you precious help!!

**Comment by srio** [comment]
In fact if I just do: 

```
cd shadowOui
python setup.py develop
```

it works. 

However, the issue is still valid if we want to "install"

Cheers, M

**Comment by lucarebuffi** [comment]
Dear Manolo,

the proper way to "install" the add-on is through pip:

cd ...../ShadowOui
python setup.py sdist 
python -m pip install ./dist/ShadowOui_x.y.z.tar.gz --update

THIS is the proper way to install it.

**Comment by lucarebuffi** [comment]
In the develop phase you should type the command:

python setup.py sdist develop
