### ISSUE TITLE
about the lost flag

### ISSUE THREAD

**Issue by tyjisinap** [lucarebuffi/ShadowOui#148]
Dear luca,
In the shadowvui I usually set  zero as lost flag, then the plotxy will handle this ray as lost. but in shadowoui  the zero can not be as lost flag,  is there a rule for this flag?

Yajun Tong

**Comment by lucarebuffi** [comment]
There are no differences, since the lost flag is managed by the kernel Shadow3 itself. In Shadow3 the flag (column 10 of the ray array, or 9 in a zero-index system) is set as follow:

- good ray: flag = 1
- lost ray: flag < 0

**Comment by tyjisinap** [comment]
OK, Thank you!
