### ISSUE TITLE
Saving when not required

### ISSUE THREAD

**Issue by RubenReininger** [lucarebuffi/ShadowOui#149]
Dear Luca,
I have one more. The slit is saving files to disk despite having the flag no save;  as you can see in the attached file.

[Saving files even when not asked to.zip](https://github.com/lucarebuffi/ShadowOui/files/617076/Saving.files.even.when.not.asked.to.zip)

Ruben

**Comment by lucarebuffi** [comment]
Fixed, refer to 1.3.75
