### ISSUE TITLE
No Image from aperture to hybrid

### ISSUE THREAD

**Issue by RubenReininger** [lucarebuffi/ShadowOui#151]
Dear Luca,
If you run the beamline and the slit before hybrid is not saving the file, hybrid will not run. Is this the way it should be?

Should I stop?
Thanks,

Ruben

[Issues with saving mirror files 2.zip](https://github.com/lucarebuffi/ShadowOui/files/620539/Issues.with.saving.mirror.files.2.zip)

**Comment by lucarebuffi** [comment]
Why????? Contributions from on-the-field users are the most precious and important ones!!!!! 

This bug was hiding under Issue #149. It took 1 minute to fix it, please don't stop finding issues.

Refer to version 1.3.76
