### ISSUE TITLE
gui font size

### ISSUE THREAD

**Issue by tmazza79xfel** [lucarebuffi/ShadowOui#153]
dear Luca et al,

it would be good to be able to change dynamically the font size of the widget-related windows (optical element properties, python script and so on) under some preferences menu, in a similar way as displayed in the attached screenshot (from Matlab preferences menu)

thanks
Tommaso

![image](https://cloud.githubusercontent.com/assets/24431295/20963599/57ca5b2e-bc6e-11e6-8c05-f59ec43071c7.png)

**Comment by lucarebuffi** [comment]
![screen shot 2016-12-09 at 16 00 38](https://cloud.githubusercontent.com/assets/6713598/21053544/2b8d6d40-be2a-11e6-9eff-1c1c33a96fb0.png)

![screen shot 2016-12-09 at 16 00 45](https://cloud.githubusercontent.com/assets/6713598/21053547/2e079de8-be2a-11e6-8efd-fb91888fbe8c.png)
