### ISSUE TITLE
Dabam

### ISSUE THREAD

**Issue by RubenReininger** [lucarebuffi/ShadowOui#160]
Gents,
I think it is more convenient in the DABAM generator to input the length of the mirror instead of the factor.

**Comment by lucarebuffi** [comment]
You can already do it....

![screen shot 2016-12-21 at 12 13 12](https://cloud.githubusercontent.com/assets/6713598/21387213/e7cb9608-c776-11e6-8473-fabb7763b874.png)

**Comment by lucarebuffi** [comment]
The modify length has two option: (rescale + scale factor) and (fit + new length + filler)

Do you mean that instead of having a scale factor in the rescale option you would like to have a new length (and the scale factor calculated automatically)?

**Comment by RubenReininger** [comment]
Since i know the length of the mirror it will be natural to enter that number and then the factor to calculate the RMS value of height or se

Best regards

Ruben
Sent from my IPad

On Dec 21, 2016, at 05:19, Luca Rebuffi <notifications@github.com<mailto:notifications@github.com>> wrote:


The modify length has two option: (rescale + scale factor) and (fit + new length + filler)

Do you mean that instead of having a scale factor in the rescale option you would like to have a new length (and the scale factor calculated automatically)?
