### ISSUE TITLE
HybridScreen

### ISSUE THREAD

**Issue by RubenReininger** [lucarebuffi/ShadowOui#162]
Dear Luca,
I was trying to run the new version and got stuck. Initially I believed the new Hybrid was not installed. The real issue is the message 'HybridScreen " object has no attribute "ghy_nbins_y"

[Archive.zip](https://github.com/lucarebuffi/ShadowOui/files/673371/Archive.zip)

The attached file will run hybrid only on the sagittal but not in the meridional. 

Thank you.

Ruben

**Comment by lucarebuffi** [comment]
My stupid mistake, made in the last hour of the last day before vacations.

Corrected in 1.3.89

-- 

Luca Rebuffi, Ph.D.
X-Ray Optics Laboratory Supervisor

Elettra-Sincrotrone Trieste S.C.p.A
Strada Statale 14 - km 163,5 in AREA Science Park
34149 Basovizza, Trieste ITALY
Tel. +39 040 375 85 44 (office)
Tel. +39 040 375 89 07 (lab)
Tel. +39 040 375 85 12 (lab)
Mob. +39 366 656 15 21 (cod.int. #89881)

**Comment by RubenReininger** [comment]
Thanks

Ruben
Sent from my iPhone 631 681 4983

On Dec 27, 2016, at 18:23, Luca Rebuffi <notifications@github.com<mailto:notifications@github.com>> wrote:

My stupid mistake, made in the last hour of the last day before vacations.

Corrected in 1.3.89

--

Luca Rebuffi, Ph.D.
X-Ray Optics Laboratory Supervisor

Elettra-Sincrotrone Trieste S.C.p.A
Strada Statale 14 - km 163,5 in AREA Science Park
34149 Basovizza, Trieste ITALY
Tel. +39 040 375 85 44 (office)
Tel. +39 040 375 89 07 (lab)
Tel. +39 040 375 85 12 (lab)
Mob. +39 366 656 15 21 (cod.int. #89881)
