### ISSUE TITLE
ligther distribution

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#163]
git downloading takes a lot of time, basically because there is an examples directory that contains several shadow binary files:

> (oasys1env)manuels-macbook-pro:shadowOui srio$ du -s *
> 8	MANIFEST.in
> 8	README.md
> 8	README.txt
> 80	ShadowOui.egg-info
> 5216	dist
> 129272	examples   <<<<<<<<<<<<<<<<
> 2016	igor
> 7088	libraries
> 8616	orangecontrib
> 16	setup.py

The big files are for hybrid, and I thing are not relevant, moreover obsolete. 

Could you clean it?

**Comment by lucarebuffi** [comment]
done
