### ISSUE TITLE
CRL copied and getting wrong place

### ISSUE THREAD

**Issue by RubenReininger** [lucarebuffi/ShadowOui#166]
I am testing several branches of the same system.
The connected CRL was duplicated from the one that has the CRL. The CRL is supposed to write the image to disk. However, it does not. See attached directory.
Am I doing something wrong? Can one duplicate optics? Can one work with several options in the same canvas?
Thanks,

Ruben

![screen shot 2017-01-25 at 2 12 23 pm](https://cloud.githubusercontent.com/assets/15108247/22307551/09e90f60-e309-11e6-9a64-3ef925f21216.png)

[32ID.pdf](https://github.com/lucarebuffi/ShadowOui/files/730835/32ID.pdf)

This is the ows file

**Comment by srio** [comment]
It looks that indeed there is a bug writing the file. In fact, the file star.06 is missing (but mirr.06 is there). Moreover, the written files  (*.06) corresponds to the first surface of the CRL. In ShadowOui. You have 5 elements upstream (the double crystal monochromator counts twice). What one expects is the last element of the CRL, don't you?

In the meantime, if you want the files of the last surface (corresponding to shadow element 11), plug in Info widget after the CRL, go to the Python script file, change the last part to force writing the file (look to: "if True") and run it: 

```
#
#run optical element 11
#
print("    Running optical element: %d"%(11))
if True:
    oe11.write("start.11")
beam.traceOE(oe11,11)
if True:
    oe11.write("end.11")
    beam.write("star.11")
```

**Comment by srio** [comment]
The problem is in shadow3 (traceCompoundOE), not in shadowOui. I will fix it asap

**Comment by RubenReininger** [comment]
Hi Manuel,
Thanks for the hint how to deal with it. I solved the problem by putting a plane mirror.

Best regards,
Ruben


On Jan 25, 2017, at 4:39 PM, Manuel Sanchez del Rio <notifications@github.com<mailto:notifications@github.com>> wrote:


The problem is in shadow3 (traceCompoundOE), not in shadowOui. I will fix it asap
