### ISSUE TITLE
HYBRID!!

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#169]
Some things already discussed on Hybrid that I think should be changed: 

- Hybrid refuses to run if beam is not cut. We agreed that the should be turned into a warning, and to control the value for switching hybrid-calculation on/off under the user responsability

- Hybrid refuses to run if plugged to some elements. 
    - Transfocator should be accepted (like CRLs are)
    - I personally would like to plug it to other devices, including just a source. May be add another option in the pulldown menu to add "any element" to screen/mirror/CRL, and let the user take risks and understand what is doing....

**Comment by lucarebuffi** [comment]
Dear Manolo,

the first point has already and largely been discussed with Xianbo, he agreed on everything. It will be implemented soon.
Regarding the second point, I agree with the transfocator. Please discuss the rest with Xianbo.
