### ISSUE TITLE
testing OASYS 1.0

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#170]
I tested Oasys 1.0 in my mac

- The binary package works well :)

- I found some errors doing the "manual" installation. 
    - bare oasys installs well using the script https://github.com/srio/oasys-installation-scripts/blob/master/install_oasys_using_virtual_environment.sh
    - after starting oasys I installed shadowOui from the add-ons menu. Il loads the folders but the widgets are not there. I tried few times without success. 
    - then I tried to install shadowOui manually using: https://github.com/srio/oasys-installation-scripts/blob/master/update_addons.sh
         - It first gave an error that I fixed changing in the setup.py  'oasys>=1.0.0', by  'oasys', (I checked and indeed oasys is installed)
        - then again the shadowOui folders appear but the widgets are missing. I get this messages: 

```
...
  File "/Users/srio/OASYS_VE/shadowOui/orangecontrib/shadow/util/shadow_util.py", line 15, in <module>
    from oasys.widgets.gui import OasysPlotWindow
ImportError: cannot import name 'OasysPlotWindow'
Could not import 'oasys.widgets.tools.ow_python_script'.
...
```

In fact. "from oasys.widgets.gui import OasysPlotWindow" gives an error in my python...

Hope this helps to fix it...

**Comment by lucarebuffi** [comment]
Manolo, nothing is realeased in pypi.....that copy was for evaluation only in MAC.
