### ISSUE TITLE
Capillary widget: Error message

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#171]
Hello Luca, 
I am with a user that is running the capillary. It seems to work well but at the end it displays an error message: 

![image](https://cloud.githubusercontent.com/assets/502315/24611940/0f2f0cee-1884-11e7-9837-15fd774e3ddb.png)

This error prevents him to make a loop!

Thanks!!! M

**Comment by lucarebuffi** [comment]
There is something wrong in the permissions. Try to remove the "/" character form the file name....

**Comment by srio** [comment]
Apparently there is no place where this file name is defined.

**Comment by lucarebuffi** [comment]
![screen shot 2017-04-03 at 20 47 51](https://cloud.githubusercontent.com/assets/6713598/24625312/e6606ae4-18ae-11e7-8111-cb0a1fbd5f84.png)

**Comment by lucarebuffi** [comment]
Tab "Simulation", box "Simulation Management"; that file name is taken as a template for the rest of the files.

**Comment by srio** [comment]
Ok that works. But there is still a chicken egg problem I think. You have to go trough error message once then the file is created.
Then you have to select it and run again...
I can work with it now !
thanks
W

On 04/04/2017 11:29, Manuel Sanchez del Rio wrote:
>
> Wouter, before submitting the issue, could you try  pick a file with the browser (button with ...) and see what happens?
>
>
>
> On 04/04/2017 10:41 AM, Wouter VAN BEEK wrote:
>> Thanks!
>>
>> However please have a look at this: I give delme.xy in the Output File name. It seems there is some hard coding added to the file name it always adds the '/' then 'myname' and 'Instrumental Broadening.dat'
>> the '/' and 'Instrumental Broadening.dat' I cannot get rid of.
>> W

![image](https://cloud.githubusercontent.com/assets/502315/24651698/0f21d1cc-192f-11e7-9821-01d675d3d6ff.png)

**Comment by lucarebuffi** [comment]
I see, maybe this happens in Linux for some reason I never met. This error doesn't happen in Mac. Could you please tell the user to send me his OWS file?

**Comment by lucarebuffi** [comment]
I'd like to share with him, since he is the first known user of XPRD widget :D

**Comment by lucarebuffi** [comment]
Fixed
