### ISSUE TITLE
ruling parameters in spherical / elliptical grating

### ISSUE THREAD

**Issue by tmazza79xfel** [lucarebuffi/ShadowOui#172]
when the ruling parameters are specified as "polynomial line density" the definition is straightforward in case of a plane grating. 
in case of a curved grating there is an ambiguity, namely: is the polynomial referred to the surface or to the projection of a flat face normal to the pole vector?
thanks
Tommaso

**Comment by srio** [comment]
Hello, 
I believe it is not on the surface, but on the plane XY. 

In fact, you can check in https://github.com/srio/shadow3/blob/master/src/fortran/shadow_kernel.f90 line 8453 how the ruling density is built from the polynomial coefficients RUL_A*: it uses DIST,  that is previously defined ad DIST = PPOUT(2), which means that it is the Y coordinate of the outcoming ray. Therefore DIST is measured on the XY plane, not in the grating surface. 

I hope this clarify the question.

**Comment by tmazza79xfel** [comment]
thanks a lot!
