### ISSUE TITLE
change in new silx

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#173]
silx 0.5 to be released next week requires in 

...OASYS_VE/oasys1/oasys/widgets/gui.py

change 

from silx.gui.plot.BackendMatplotlib import BackendMatplotlibQt

to 

from silx.gui.plot.backends.BackendMatplotlib import BackendMatplotlibQt

**Comment by lucarebuffi** [comment]
This is huge. It must be tested in deep, before releasing. Since we are releasing Oasys 1.0 official, I prefer to posticipate it and do a deep test.
