### ISSUE TITLE
Energy shift in grating mono

### ISSUE THREAD

**Issue by RubenReininger** [lucarebuffi/ShadowOui#178]
I attach an example of entering the angles of  incidence and diffraction in mradians and degrees. 10 digits in each
When the input is in mrad  there is a shift in the energy at the exit slit plane.

[Grating digits.ows.zip](https://github.com/lucarebuffi/ShadowOui/files/1212393/Grating.digits.ows.zip)

**Comment by lucarebuffi** [comment]
Shadow needs those angles in degrees. I modified the calculation from mrad/ from deg for gratings by rounding with 10 digits for degs and 7 digits for mrads.
