### ISSUE TITLE
Empty element

### ISSUE THREAD

**Issue by RubenReininger** [lucarebuffi/ShadowOui#179]
I was using the empty element to rotate the image.
When doing so I get an error along one direction.
See attached example.

[Empty element.ows.zip](https://github.com/lucarebuffi/ShadowOui/files/1212401/Empty.element.ows.zip)

**Comment by lucarebuffi** [comment]
The reflection angle should be 180

**Comment by lucarebuffi** [comment]
here is the corrected version

[Empty element.ows.zip](https://github.com/lucarebuffi/ShadowOui/files/1216647/Empty.element.ows.zip)
