### ISSUE TITLE
hybrid screen doesn't show in the info->python scripts

### ISSUE THREAD

**Issue by tyjisinap** [lucarebuffi/ShadowOui#182]
how to use the hybrid screen in the python scripts? the hybrid screen doesn't show in the info.
Yajun Tong

**Comment by lucarebuffi** [comment]
Dear Yajun, it must be said that It shouldn't show, since it is not an optical element. Hybrid "Screen" modify the result of the standard ray-tracing, but it doesn't alter the optical layout. The ShadowOui concept of it is different of the old ShadowVUI implementation.

**Comment by srio** [comment]
I think what Yajun means is that the fact that using a hybrid screen is not reflected in the info widget not in its python script. True. It is not reflected and the python script will run the system without introducing the effect of the hybrid screen. The hybrid screen is only implemented in shadowOui and can only be used with it. It is not implemented in shadow3 so cannot be used in the script. The implementation in shadowOui is complex to make its use simple, so it is not possible to reimplement it at lower level in shadow3. 
There are other features in shadowOui that are not transmitted into the automatically generated script, like it you inset a "python script widget" or inject reflectivity calculated with other add-ons.

**Comment by tyjisinap** [comment]
Dear Luca,
Thanks you, I will try  the new coherence raytrace widgets that you show us in this morning. I hope I can install on the Ubuntu.
Best regards.
Yajun Tong

**Comment by tyjisinap** [comment]
Dear srio,
yes, that's my meaning. 

yajun
