### ISSUE TITLE
More than one energy

### ISSUE THREAD

**Issue by RubenReininger** [lucarebuffi/ShadowOui#33]
I could not generate  a gaussian beam with two energies.

**Comment by lucarebuffi** [comment]
Dear Ruben, what do you mean with gaussian beam? Spatial type or photon energy distribution?

In this moment bi(multi)-modal distribution are not supported, thank you for the suggestion!

**Comment by RubenReininger** [comment]
Sizes and divergences are gaussians (to simulate an undulator beam

Ruben
Sent from my cell

On Oct 13, 2015, at 9:55 AM, Luca Rebuffi <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Ruben, what do you mean with gaussian beam? Spatial type or photon energy distribution?

In this moment bi(multi)-modal distribution are not supported, thank you for the suggestion!

**Comment by lucarebuffi** [comment]
the problem is in Shadow3 (fortran), when divercengy limits are too small, ti refuses to generate the beam and kills the application. We managed at the gui level putting a lower boundery for the limits, and the possibility to specify "no limits"

**Comment by RubenReininger** [comment]
Dear Luca,
Is the problem solved?

I should get two energies at the end of the optical elements.

Regards,

Ruben

On Oct 15, 2015, at 8:29 AM, Luca Rebuffi <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #33<https://github.com/lucarebuffi/ShadowOui/issues/33>.

**Comment by lucarebuffi** [comment]
I am releasing a set of bug fixing/improvements asap.

**Comment by RubenReininger** [comment]
OK. Thanks

On Oct 15, 2015, at 8:48 AM, Luca Rebuffi <notifications@github.com<mailto:notifications@github.com>> wrote:


I am releasing a set of bug fixing/improvements asap.

**Comment by lucarebuffi** [comment]
![screen shot 2015-10-15 at 3 55 14 pm](https://cloud.githubusercontent.com/assets/6713598/10515749/2c19525e-7355-11e5-9e0e-ac9e219ce3d5.png)

**Comment by RubenReininger** [comment]
This is what I mean

[cid:5A543DC4-9320-4B91-A217-EA3B134FD020@aps.anl.gov]
On Oct 15, 2015, at 8:55 AM, Luca Rebuffi <notifications@github.com<mailto:notifications@github.com>> wrote:


[screen shot 2015-10-15 at 3 55 14 pm]<https://cloud.githubusercontent.com/assets/6713598/10515749/2c19525e-7355-11e5-9e0e-ac9e219ce3d5.png>

**Comment by lucarebuffi** [comment]
it will be released very soon, I hope today.

**Comment by srio** [comment]
Two comments: 

it seems that even if "no limits" is set, the values are still used:
![image](https://cloud.githubusercontent.com/assets/502315/10525813/2c42e9f2-7387-11e5-8c1b-1ed22d995595.png)

If "no limits" is set, the limit values in start.00 must be set to zero

2) The "two energy lines" is working well. However, the plot is confusing, because the two peaks are cropped and the arrow indicating the FWHM seems to give a flat distribution. 

Unfortunately the limits of the histogram cannot be changed in the histogram widget, so this is may be an improvement for the future.

**Comment by lucarebuffi** [comment]
Limits are fixed: my mistake.

Regarding the plot widget: ask PyMca5 team!!!!

**Comment by lucarebuffi** [comment]
N.B. the 1e-5 restriction on limits is not functional, there are other situations where Shadow closes.
Only the reimplementation of the Shadow3 fortran code could completely fix the problem

**Comment by srio** [comment]
OK, I will do it asap (not before Nov, however). 

Regarding the zoom out in histo plot: 
- I managed to zoom out in my Mac using the "two fingers" in the pad
- I agree, some limits definition should be available in the plot widget (to be checked with Armando). However, these limits affect only the plot, and the histogram is not recalculated. 
- It may be interesting to add limits selection in the widget parameters. This will need to recompute the histogram. I think it is important when accumulating histograms to be sure histogram have exactly the same limits (I imagine now is determined by the first histogram). To be discussed.
