### ISSUE TITLE
Automatically save workspace every X minutes

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#4]

**Comment by lucarebuffi** [comment]
Added Global Preference "Automatically Save every" (Menu Orange->Preferences)

**Comment by lucarebuffi** [comment]
Oasys creates an automatic backup file:

- automatic_save_xxxxxxx.ows~ (where xxxxxxx is a univocal identifier), if the workspace is not yet saved by the user
- <file name>.ows~ , if the workspace is already saved in a file by the user
