### ISSUE TITLE
FOCNEW: missing function on ShadowOui!

### ISSUE THREAD

**Issue by lucarebuffi** [lucarebuffi/ShadowOui#44]

**Comment by lucarebuffi** [comment]
A widget with this old functionality is required!

**Comment by srio** [comment]
focnew is now available in ShadowTools

Create a new widget? Or integrate the text output in the info widget? To be discussed.


I think graphics of focnew are not very useful, as they are better done by ray_prop (now available  in ShadowLobExtensions: beam.ray_prop()

To be discussed.
