### ISSUE TITLE
Improvements in the APS widget for simulated profiles

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#45]
- rename the widget to something not containing APS line "surface error simulator" "simulated profiles, etc"

-Change icon

- use the new error_profile.py that implements new simulate_* functions

-The widget should contain two panels one for direction along the length "L" and the other along the width "W". Both have identical inputs: 
   - type of profile (Gaussian G, Fractal F, or Experimental E). A Pulldown menu can be used to select which one is wanted. 
  - type of error: slope or height and its value (as already implemented) [for G or F]
  - beta (exponent of the power law) for F
  -correlation length for G
  -file for E (already implemented)

-It should calculate the StDev values, beta, correlation length and may be PSD of the main profiles along L and W 

- Put all inputs in meters, and at the moment to write the file (for Shadow) select the wanted units 
(cm, mm, m)

-(It seems that the widget at it is now does not work with external files).

**Comment by lucarebuffi** [comment]
Simulation from 1D profiles fixed

**Comment by lucarebuffi** [comment]
The widget will be replaced by a new one, with more general algorithms and features
