### ISSUE TITLE
Geometrical sources (and may be other sources) crashes when using optimization with slit from file 

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#46]
The problem is the well known issue with the string management. 
FILE_BOUND should be "corrected"
Test: The tutorial example number 24

**Comment by lucarebuffi** [comment]
It is not. FILE_BOUND string is already corrected. Apparently the file indicated by the user is not arriving at the fortran level, that indicates:

Error opening file: NONESPECIFIED
