### ISSUE TITLE
preprocessor waviness: send dimensions and activate surface errors

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#5]
When connecting a wire from the waviness preprocessor to an optical element:
1) The name of the file should be copies (this is already done)
2) the surface error/spline should be activated
3) The mirros dimensions = finite should be activated
4) the mirror dimensions should be transferred from waviness widget to o.e. widget
5) May be: a warning message could inform the user

**Comment by lucarebuffi** [comment]
do it for reflectivity too
