### ISSUE TITLE
screen from external file: error in checking file

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#52]
Like in example 26, when defining a slit with "Aperture shape"=External, it gives an error: 

checkFileNames() takes 1 poitional argument but 2 were given

**Comment by lucarebuffi** [comment]
same error?

**Comment by srio** [comment]
I got it: 

The problem is that the file name for the external script is ignored by the interface. The reason is that the shadow variable is FILE_SCR_EXT, and the screen widget uses file_SRC_ext. There is no error because python creates new variables on the fly. Please replabe  FILE_SRC_EXT (bad) by FILE_SCR_EXT (ok).

**Comment by lucarebuffi** [comment]
The problem is in ShadowLibExtension.py, method set_screens, row 724. Not a ShadowOui Issue.

**Comment by srio** [comment]
Glup!!  Fixed, now I think you have to change also ow_screen_slits.py

By the way, better that you update shadow3. I also removed may "STOP" that I forgot!!!

**Comment by lucarebuffi** [comment]
It is better not to change the name of the python parameter file_src_ext in the method signature (impact is huge in ShadowOui). Just fix the bug.

**Comment by lucarebuffi** [comment]
No impact on ShadowOui, parameters are passed without parameter name

**Comment by srio** [comment]
I think is better to fix... Does it affect to other widgets in addition to the Screen-Slit one?
