### ISSUE TITLE
Compound Elements: Allow to write start.xx and end.xx files

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#56]
These files are very very useful for debugging. Write then if option "Files to write out"="All"
In all compunnd elements (ow_kb.py ow_dcm.py, lens, crl and transfocator) modify: 

        write_star_files, write_mirr_files = self.get_write_file_options()
        beam_out = ShadowBeam.traceFromCompoundOE(self.input_beam,
                                                  shadow_oe,
                                                  write_star_files=write_star_files,
                                                  write_mirr_files=write_mirr_files)

and add the start and end file flags: 

        write_star_files, write_mirr_files, write_start_files, write_end_files= self.get_write_file_options()
        beam_out = ShadowBeam.traceFromCompoundOE(self.input_beam,
                                                  shadow_oe,
                                                  write_star_files=write_star_files,
                                                  write_mirr_files=write_mirr_files,
                                                  write_start_files=write_start_files,
                                                  write_end_files=write_end_files,
)

**Comment by lucarebuffi** [comment]
Start and End files are not used anymore. It is not correct that the "All" option behaves differently from normal OE and Compound OE. Moreover, it can cause the production of hundreds of files with no reasons for the normal user.
If the purpose is debugging a dedicated option on the combobox has been created: "Debug (All + start.xx/end.xx)".
