### ISSUE TITLE
Add a PGM (Plane Grating Monochromator) calculator

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#6]
Add in Shadow Utility a widget for calculating variables of PGM. 
Ask Ruben for functionality

**Comment by lucarebuffi** [comment]
It will be implemented as an Utility tab in gratings, as we did for DCM distance calculator for crystals.

**Comment by RubenReininger** [comment]
I think this will be a good addition. It could be a calculator that spits the VLS parameters

**Comment by RubenReininger** [comment]
Of course in case of a VLS based PGM

**Comment by lucarebuffi** [comment]
Dear Ruben, could you provide an algorithm that is satisfactory to you?

**Comment by srio** [comment]
In the principle, I agree. But we will need also calculators for calculating the radii of curvatures (focusing conditions), Rowland distances, Bragg angles, etc. etc. I think it is not a good idea to write so many calculators, and the place for these tools is more XOPPY than SHADOWOUI. 

In my opinion the first approach should be to write a python script to do that and include it in a example grating workspace. As examples, I included in my tutorials workspaces scripts that do  some calculations, like the sagittal radius for crystals in ex18_sagittalfocusing. 

```
import xraylib 
import numpy

import scipy.constants.codata
codata = scipy.constants.codata.physical_constants
codata_c, tmp1, tmp2 = codata["speed of light in vacuum"]
codata_h, tmp1, tmp2 = codata["Planck constant"]
codata_ec, tmp1, tmp2 = codata["elementary charge"]
tocm = codata_h*codata_c/codata_ec*1e2

#
# define miller indices, distances and photon energy in eV
#
hh = 1
kk = 1
ll = 1
p = 3000.0
q = 1000.0
crystal_name = "Si"
photon_energy_ev = 20000.0

#
# get crystal info from xraylib
#
cryst = xraylib.Crystal_GetCrystal(crystal_name)
dspacing = xraylib.Crystal_dSpacing(cryst,hh,kk,ll )
print("dspacing: %f A \n"%dspacing)

sin_theta = (tocm/(photon_energy_ev*2.0*dspacing*1e-8));

rt=2*p*q/(p+q)/sin_theta;
rs=2*p*q*sin_theta/(p+q);

print("Using crystal: %s %d%d%d at E=%.3f eV"%(crystal_name,hh,kk,ll,photon_energy_ev))
print("               p=%.3f, q=%.3f"%(p,q))
print("Rtangential = %f, Rsagittal=%f"%(rt,rs))
```

which displays: 


```
>>> 
Running script:
dspacing: 3.135416 A 

Using crystal: Si 111 at E=20000.000 eV
               p=3000.000, q=1000.000
Rtangential = 15173.303377, Rsagittal=148.286760
>>> 
```
It is written in such a way that is easy to customize for other crystal and reflection, and it also shows how to use some tools (here xraylib and the import of physical constants from scipy). 

OK, this is what I think, but I am not against to write it if you consider useful. 

PS: In any case, the formulas are needed for the parameters calculations.

**Comment by lucarebuffi** [comment]
I want to remember that the DCM utility doesn't deal with calculations like bragg angle, etc.
It is a real SHADOW utility, calculating distances between the crystals needed by the simulation, in function of an already calculated bragg angle and the distance with a further OE. It doesn't contain any physics.
