### ISSUE TITLE
Dabam widget: wrong!

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#60]
Opening the DABAM widget reproduces exactly the "Height profile" widget. 

I hope you have not lost the work you did for DABAM!!!!

![image](https://cloud.githubusercontent.com/assets/502315/12265915/52d5e76e-b940-11e5-91a1-f713fee80b75.png)

**Comment by lucarebuffi** [comment]
![screen shot 2016-01-12 at 19 14 55](https://cloud.githubusercontent.com/assets/6713598/12272460/e2daf8c0-b960-11e5-8ea0-746422216ec0.png)

This is what I have after updating from pypi my oasys application (not Pycharm!). Please check the status of your development environment.
