### ISSUE TITLE
Waviness widget

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#61]
Starting Waviness widget, and "Reset Fields" (or not) I get an error when clicking "Calculate Waviness":

![image](https://cloud.githubusercontent.com/assets/502315/12265985/c28601d4-b940-11e5-9068-082d5b6b82d5.png)

**Comment by lucarebuffi** [comment]
Please verify your environment. I am not able to reproduce this error, widget is working properly.

**Comment by lucarebuffi** [comment]
Please verify you don't have matplotlib 1.5.0. If so it must be uninstalled and replaced by matplotlib 1.4.3.
