### ISSUE TITLE
Lens and CRL widgets: attenuator coefficient CAN be zero

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#63]
Please remove the checking for the attenuation coefficient. It can be zero for non-absorbing lenses. Same problem for the CRL (it seems that for transfocators is OK)

![image](https://cloud.githubusercontent.com/assets/502315/12320122/1775c3f2-baa7-11e5-9dec-67300a0e2f74.png)

**Comment by lucarebuffi** [comment]
My mistake, it was corrected for the transfocator and forgotten to be done in the other OE.
