### ISSUE TITLE
Geometrical Source Energy Units

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#65]
In a geometrical source I select the energy as Photon energy, like: 

![image](https://cloud.githubusercontent.com/assets/502315/12353560/64eb1210-bb90-11e5-8a4d-08ac26d88abf.png)

Then I save the workspace. When I reload the workspace I always get units in Angstroms:
![image](https://cloud.githubusercontent.com/assets/502315/12353612/b1a199a8-bb90-11e5-9139-d5a581c61129.png)

**Comment by lucarebuffi** [comment]
I am not able to reproduce the error (After saving the workspace I have the correct units). Could you please go in detail of the steps you did?

**Comment by srio** [comment]
1) Open ShadowOui, insert in the empty canvas a Geometrical Source, Set Units to Energy/eV, Run SOurce
2) Save workspace to /tmp/test_energy_units.ows
3) Quit ShadowOui
4) Open ShadowOui, and load  /tmp/test_energy_units.ows
5) Units are Angstroms :(

Here the file (remove the TXT extension!!)
[test_energy_units.ows.txt](https://github.com/lucarebuffi/ShadowOui/files/91904/test_energy_units.ows.txt)

**Comment by lucarebuffi** [comment]
Gotcha. Depends from a functionality under development (Default and Workspace units of measure), it will disappear when finished.

**Comment by lucarebuffi** [comment]
Please pull oasys repository and the bug disappear.
