### ISSUE TITLE
FOCNEW

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#66]
For implementing focnew, I propose two solutions: 

* The simple one:  add a tab "focnew" in the Info widget with the text produced by focnew: 
```
tkt2 = Shadow.ShadowTools.focnew(beam,nolost=1,mode=1)
print(tkt2["text"])
```

* The one for perfectionist is to create a new postprocessor widget that runs focnew and also ray_prop and display the graphics. As a guide, I implemented the functionality in two scripts in the tutorials example 24 (transfocator), for focnew:
https://github.com/srio/ShadowOui-Tutorial/blob/master/script24b.py
and for ray_prop: 
https://github.com/srio/ShadowOui-Tutorial/blob/master/script24c.py

**Comment by lucarebuffi** [comment]
FocNew is already implemented with its own widget, please take a look.
