### ISSUE TITLE
Toroidal elements: Never cylindrical

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#68]
In the Toroidal mirror, grating and crystal, please remove the "Cylinder Parameter" menu. 

In principle, a toroid+cylinder is the same effect as sphere_cylinder, and I think that SHADOW does not do anything on toroids (not 100% sure)

**Comment by lucarebuffi** [comment]
Let's test it before touching it.

**Comment by srio** [comment]
Confirmed. FCYL is irrelevat if toroidal.
