### ISSUE TITLE
How to write OE parameter to start.xx ?

### ISSUE THREAD

**Issue by tyjisinap** [lucarebuffi/ShadowOui#69]
Dear lucarebuffi,
I set to "File to write out : All", but there is no start.xx file. and for the source, there is no such a option. or is there a simple way to change one of the OE or Source parameters in a loop? 
Thank you!

**Comment by lucarebuffi** [comment]
We initially decided to not write the start.xx/end.xx files in ShadowOui. 
By the way, please check issue #58 -> very soon this option will be available as a Debug mode.

The possibility to change values during a loop is not implemented yet, but it will be.

**Comment by tyjisinap** [comment]
Thank you very much!

**Comment by lucarebuffi** [comment]
Thank you!

**Comment by lucarebuffi** [comment]
Implemented, it will be available with the next release.
