### ISSUE TITLE
Plot XY: strange behavious when one column is energy

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#72]
It seems there are some problems with limits and unit conversion when using energy column.
For example: 

1) (X,Z) plot (OK):
![image](https://cloud.githubusercontent.com/assets/502315/12416181/2d2378dc-bea0-11e5-84a9-c0a50ee98136.png)

2) I ONLY change the X column to Energy: 

Strange effects: 
i) The minimum of Y is set to zero (even if I decided the range). And the max is 1e7??
ii) The calculation of limits for energy are extremely large 

![image](https://cloud.githubusercontent.com/assets/502315/12416226/77e71fe0-bea0-11e5-8e6e-8f16a9250e13.png)

PS: Do you really prefer the info panel at the left? I prefer the old one at the right.  To better use the space, could be may be better at the bottom (or top?) in thee columns:
```
Intensity: xx      Total good rays: xx  FWHM X: xx
Total rays: xx     Total Lost rays:  xx  FWHM Y: xx
```

**Comment by lucarebuffi** [comment]
I am working on User's units (Issue 3), Window dimensions (issue 48) and Layout (issue 47).
Please let me finish, I have not released yet anything and everything it is under development!

The position of the info box at right is a request from users, but I am still testing solutions. 
While using the info box in top or bottom position the plot image is completely squeezed, so the only choice is between left and right. By the way, I am also reducing the window size significantly.

**Comment by srio** [comment]
No problem, sorry. I am also creating new workspaces from old runs. I can wait, but it is good to list the problems found, even if they are corrected automatically later...

**Comment by lucarebuffi** [comment]
Sure it is and please do it, I am only advising you that some functionalities completely under development, and maybe it also weird to fill the public issue tracker with temporary invalid entries.

**Comment by lucarebuffi** [comment]
I verified with the old version (the one available in Pypi) and the problem is present also there. So the issue is valid.

**Comment by lucarebuffi** [comment]
Windows dimension are going to be reduced (issue 47), position of the info box at left is a request from beta testers, and it is under evaluation/test. Top and Bottom position is not a good choice because the plot image would be to squeezed.
