### ISSUE TITLE
Sources widgets: give also the possibility to write begin.dat

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#78]
I see you implemented: 
![image](https://cloud.githubusercontent.com/assets/502315/12538363/377a4d42-c2d8-11e5-88de-b9de281b60b3.png)

Very good. To be perfectionist, may I ask to implement: 

-None
-begin.dat
-begin.dat+Debug(start.xx/end/xx)

**Comment by lucarebuffi** [comment]
Sure!
