### ISSUE TITLE
Bragg widget - List of available crystals

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#80]
The list of available crystals should come from xraylib. The method to extract it is not yet available, but it will be soon:

crystals = xraylib.Crystal_GetCrystalsList()

(see https://github.com/tschoonj/xraylib/issues/30 )

In the meantime, the list could be hardcoded in a pulldown menu. 

These are the names (% grep "#S " data/Crystals.dat | awk '{print $3}' ) :

Si
Si_NIST
Si2
Ge
Diamond
GaAs
GaSb
GaP
InAs
InP
InSb
SiC
NaCl
CsF
LiF
KCl
CsCl
Be
Graphite
PET
Beryl
KAP
RbAP
TlAP
Muscovite
AlphaQuartz
Copper
LiNbO3
Platinum
Gold
Sapphire
LaB6
LaB6_NIST
KTP
AlphaAlumina
Aluminum
Iron
Titanium

**Comment by lucarebuffi** [comment]
N.B. check the tutorials, with this modification all the crystals must be specified again

**Comment by srio** [comment]
The key point is that in xraylib, one thing is the compound parser,  to build the table and amount of different elements in a compound, and another thing is a crystal name, where the particular crystal name must correspond to a structure stored in xraylib. 

For example, H2O works as a compound but not as a crystal, because the crystal structure correponding to H2O (or ice) is not (yet) included. 

Therefore, I suggest something that you have: 
```
self.DESCRIPTOR = ShadowPhysics.checkCompoundName(self.DESCRIPTOR)
```
but specific for crystals, like: 

```
self.DESCRIPTOR = ShadowPhysics.checkCrystalName(self.DESCRIPTOR)
```

Certainly prerefl should call checkCompoundName and bragg checkCrystalName.

You can simply check with "try" to import the crystal: 
```
try: 
    tmp = xraylib.Crystal_GetCrystal(crystal_name)
except: 
   print("Not a valid crystal name: %s"%crystal_name)
```
