### ISSUE TITLE
Refractor interface widgets: some problems

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#82]
1) Lenses could receive data from prerefl preprocessor. When trying to connect prerefl to the refractor interface it says: 
![image](https://cloud.githubusercontent.com/assets/502315/12672149/76126f68-c674-11e5-8c89-9f0123eac52b.png)

2) When entering with the browser the prerefl file it says: 
![image](https://cloud.githubusercontent.com/assets/502315/12672284/4cb42cb4-c675-11e5-9b53-bdab8bedcbd6.png)

**Comment by lucarebuffi** [comment]
First one is Fixed. I am not able to reproduce the second error, please detail the actions you did.
