### ISSUE TITLE
is it a bug?

### ISSUE THREAD

**Issue by tyjisinap** [lucarebuffi/ShadowOui#83]
![screenshot from 2016-01-31 09 11 05](https://cloud.githubusercontent.com/assets/16676119/12699570/c8964f34-c7fa-11e5-8791-938594a6d40f.png)

The histgram and spot look like different.

**Comment by lucarebuffi** [comment]
Nope, you probably unintentionally flipped the image with the second last button.

**Comment by lucarebuffi** [comment]
By the way, usually when you filp the image the histogram is flipped as well. Could you please send me the workspace?

**Comment by tyjisinap** [comment]
Sorry, I can't get the same image, and I have updated the shadow3 and shadowOui today.

**Comment by lucarebuffi** [comment]
Ok! Please keep me informed if you have the same problem in future.

**Comment by tyjisinap** [comment]
By the way, do you have a example of using hyperbolid crystal in laue mode? I don't know how to get the focus spot directly .
My email tongyajun@sinap.ac.cn 
Thank you very much!

**Comment by tyjisinap** [comment]
Ok!

**Comment by lucarebuffi** [comment]
I'm sorry not. I will be asking Manuel to work together on it.

**Comment by tyjisinap** [comment]
Thank you very much!
