### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'user_units_to_cm'

### ISSUE THREAD

**Issue by tyjisinap** [lucarebuffi/ShadowOui#84]
I updated the ShadowOui and it often gives this error information.

**Comment by srio** [comment]
Try to update oasys as well.

**Comment by tyjisinap** [comment]
I use  pip install oasys  --upgrade ,  but it tell me everything is up-to-date.

**Comment by lucarebuffi** [comment]
try pip install oasys==0.1.10 --upgrade

**Comment by lucarebuffi** [comment]
sometimes pip fails, it already happened with a beta tester. During the last three weeks we worked a lot on the basic code (oasys and shadow3), so it is mandatory to update everything before doing a test.

**Comment by tyjisinap** [comment]
I try the command above,  but the error is still there.

**Comment by tyjisinap** [comment]
I reinstall shadow3 and it's OK

**Comment by lucarebuffi** [comment]
Ok, I recognise now that the missing variable belongs to the shadow3 distribution, I apologise for that.
