### ISSUE TITLE
Hybrid error

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#86]
I get this error when running hybrid_mirror.ows from tutorials (and also hybrid_twoslits):

![image](https://cloud.githubusercontent.com/assets/502315/12724549/afb4ca94-c90e-11e5-8e92-4ea7a0dc9fea.png)

**Comment by lucarebuffi** [comment]
I don't have this error. Please use the example in ShadowOui.
![screen shot 2016-02-01 at 19 00 10](https://cloud.githubusercontent.com/assets/6713598/12726103/103c3490-c916-11e5-963f-3f351c51dfe6.png)
