### ISSUE TITLE
Compound KB 

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#90]
I found two problems: 

1) easy:
If dimensions = Infinite then 
![image](https://cloud.githubusercontent.com/assets/502315/12882879/c4d61b26-ce54-11e5-8c30-ce84180a3a6e.png)

In principle, the dimensions must be finite only if Surface Error=Yes. 

2) If I select independently: 
  - Relectivity Kind Mirror (and file)
 - Surface error Yes (and file) 

they work. But if I select the two at the same time, python crashes.
Like all python crashes, it it usually my fault (shadow3). But if I run the same system in a script it works fine. I really do not know where the problem can be. I spent a lot of time without being able to identify where is the problem. If you can test, I appreciate!

**Comment by lucarebuffi** [comment]
1) That was a very stupid mistake. Fixed.

2) I have not the same problem. See fi
![screen shot 2016-02-08 at 21 57 56](https://cloud.githubusercontent.com/assets/6713598/12898881/292c5586-ceaf-11e5-828d-3943e9af3afc.png)

I created this example, where the KB receives from preprocessors both reflectivity and error profile files (both Horizontal and Vertical). 

I run the simulation and I have not any error:
![screen shot 2016-02-08 at 21 57 44](https://cloud.githubusercontent.com/assets/6713598/12898914/55e4dca6-ceaf-11e5-80be-700e52f245dd.png)

Send me your workspace and files.

**Comment by lucarebuffi** [comment]
Possibly the error is in Linux for the usual string problem. The only difference I see is that usually I encode the strings before passing them to shadow as bytes(<a string>, 'uft-8), then before calling the trace method I use the metod self_repair() you can find in the shadow_objects.py module.
Strings in Compound OE are treadted in ShadowLibExtension.py directly, but differently <a string>.encode('utf-8'). Maybe it is necessary to uniform the way to pass strings to shadow (with the first method that works for sure)

**Comment by lucarebuffi** [comment]
I will check in Linux asap.

**Comment by srio** [comment]
Thanks a lot. In my Mac, it works. I send you the workspaces by email.

**Comment by lucarebuffi** [comment]
Dear Manolo, I verified that the problem is in Linux. I think it is correlated with the strings problem.
I will modify the shadow3 python files and try to homogenize the way we treat the strings as a test. If it works I will send you the modifications in order to fix them in the official distribution.

**Comment by lucarebuffi** [comment]
I fixed the problem, here the ShadowLibExtensions.py file corrected.
[ShadowLibExtensions.py.zip](https://github.com/lucarebuffi/ShadowOui/files/132948/ShadowLibExtensions.py.zip)
