### ISSUE TITLE
Slope Errors: ideas for enhancement

### ISSUE THREAD

**Issue by srio** [lucarebuffi/ShadowOui#91]
Two ideas:

1) In the optical elements, it is very useful the "View" button that displays the surface error file. It would be more useful is it also displays the slope error rms (as in Dabam, Height profile and waviness).

2) Dabam works very well: select a file and go. If possible add a "glass clock" or "running" cursor to indicate it is working. Sometimes it takes some time and we do not see reactions. Another thing to improve is to save in some way the number of profile used. If I use for my calculations, for example, profile 26, this information is lost when I save and reopen the workspace. Could be possible when one clicks on a profile to copy the entry number to a new box, so this item would be automatically saved by Orange?

**Comment by srio** [comment]
Ah, another thing: in DABAM there are profiles not centered, I mean they start from zero to Length and not from -L/2 to L/2 as expected by shadow. Could be possible to put the center in the middle when generating the surface? Or better, give this possibility to the user.

**Comment by lucarebuffi** [comment]
1) and 2) are done
