### ISSUE TITLE
Compound OE: let DCM accept separate reflectivity files for first and second crystal

### ISSUE THREAD

**Issue by lucarebuffi** [lucarebuffi/ShadowOui#94]

**Comment by lucarebuffi** [comment]
This feature is particularly important: it is now impossible to differentiate the two crystals for the thermal behaviour. I think it is just a matter to change the method signature and the variable assignment.

**Comment by srio** [comment]
So, if I understand well you want to be able to define surface error files. Correct?

I do not see the interest to have different reflectivity files that would correspond to different crystal material or different reflection. Usually DCM use identical crystal type. 
In any case you can always use two separate crystals. 

Please confirm that you want surface error files and I''ll do it in shadow3.

**Comment by lucarebuffi** [comment]
No I mean diffraction profile files. 
Sometimes is useful to take into account thermal issues, and put on the first crystal a file with a bigger Darwin width, even if both the crystal have the same material. But maybe you are right, it can lead to mistakes and absurd values. I close the issue.
