### ISSUE TITLE
FocNew: Sagittal and Tangential titles are inverted

### ISSUE THREAD

**Issue by lucarebuffi** [lucarebuffi/ShadowOui#98]

**Comment by srio** [comment]
It depends: If all "O E orientation angle" are zero (usual case), then Z=Tangential and X=Sagittal; so it is correct.

If there is an odd number of O E orientation angle" = 90 deg, then the X and Z axes are exchanged, so the titles are inverted. 

It is possible to remove the SAGITTAL and TANGENTIAL labels and put only X and Z. That will be "more accurate" ;) and "less confusing".

Do you want that I do it in shadow3?

**Comment by lucarebuffi** [comment]
Yes!

**Comment by srio** [comment]
Done in shadow3
